make proxy setting optional
Setting any options to `None`, causes this type of error
with geckodriver.

```
An argument passed to the WebDriver server was invalid:
    Status: 400
    Additional info:
        noProxy is not an array: null
        Error: invalid argument
        Stacktrace:
```

Not deserialize settings if they are equal None resolves
the issue.

Signed-off-by: Maxim Zhiburt <zhiburt@gmail.com>